### PR TITLE
Add README to detail project contributing

### PR DESCRIPTION
**Pull request by HenrikOssipoff**
Added a rather large README file that describes how to work on the
project, on either Ubuntu or OS X.

Also wrote sections on code style, how virtual environments work, as
well as some reading on how to actually do your first pull request.

This was meant to be short, but turned into something rather large. It details the work of #9.

Awaiting feedback, I'm sure there's something that could be made better. Feel free to comment. If I don't hear anything before Monday, I'll merge in.

### CODE REVIEW

**Comment by fishbacon** [comment]
Made a [PR](https://github.com/HenrikOssipoff/stregsystem/pull/1) changing the `dev` to `1.7` since some might find the "you are on the bleeding edge"-banner scary and the info has the potential of being incorrect (probably not since it is all guidelines).

**Comment by HenrikOssipoff** [comment]
Good point. The reason I chose dev was because it "isn't outdated" in 3 years, but I like your point better. We'll just need to keep it semi up to date.

**Comment by fishbacon** [comment]
If we are updating to 1.8 when that time comes we will make sure to update the links.

**Comment by jones-g** [comment]
Comments on README. Followed this on GnomeUbuntu 14.10

I went with using bundled Python3 and installed pip manually by doing:
sudo apt-get install python3-pip

Went on to install git and python3.4-venv via:
sudo apt-get install git python3.4-venv

Virtual environments is now working and reporting 3.4.3 as python version.

Getting the code commands need to be shuffled a bit I think.

Did clone, went to stregsystem folder, created virtual environment activated, changed to stregsystem folder (this is now the subfolder) did pip install -r requirements.txt -> failed the file is one folder up. Perhaps switch those two commands.

I ran into not having pg_config available. This can be fixed by:
sudo apt-get install libpq-dev

python manage.py runserver now starts the server and shows a default page and /admin shows admin interface.

**Comment by HenrikOssipoff** [comment]
Right, so basically installing python3-pip will mean ensurepip works when using pyvenv-3.4. That seems simpler, I will do a quick test on a VM and adjust accordingly.

My bad on the missing change directory, will correct.

libpq-dev is documented, although with the compilation step. I'll fix that when changing to the python3-pip package.

I still like compiling manually, though -- but I'm weird like that :)

Thank you for the feedback, will ping once I've done an updated PR.

**Comment by fishbacon** [comment]
I will do a Windows install instruction this evening or Sunday if I find the time. It was pretty simple to do on 8.1 so I think it might be easy enough elsewhere too.

**Comment by HenrikOssipoff** [comment]
I wrote the changes proposed by @jones-g and rebased it all (I think it went well...).

@jones-g can you take a look again? I've tested the installation instructions against both 14.04 and 14.10 this time around -- thank you for the heads up! It seems they have not backported the fix to virtualenv yet, even though they plan on doing it.

**Comment by fishbacon** [comment]
Any progress on this?

**Pull request merged**
