### PR TITLE
Added apps for issue #10

### PR DESCRIPTION
**Pull request by fishbacon**
This is the initial design for the new models discussed in #10.
It contains a fixture (`test-fixture.json`) which can be loaded to see how the models could be used.

### CODE REVIEW

**Comment by fishbacon** [comment]
Some comments on the design:
- I would like the app `transactions` to have a different name (finance or something like that)
- The `Transaction` model should probably not reference a `Member` but rather an `Account` which a `Member` can then be tied to. (this could be a place for caching balance and possibly other stuff)
- `Tag` is as of yet unused, I think we might want to do two types of meta, one for listings and one for products, but I am unsure how we should do them.

**Comment by jones-g** [comment]
Definition of is_sale and is_payment is missing a "case" for 0. We should define a 0 transaction as either sale or payment. Payment makes no sense so I argue we label it as a sale. Could be used to track registration for events that do not have a cost.

**Comment by HenrikOssipoff** [comment]
Haven't had the time to look at this yet, hopefully will have some time tonight.

**Comment by fishbacon** [comment]
> Definition of is_sale and is_payment is missing a "case" for 0. We should define a 0 transaction as either sale or payment. Payment makes no sense so I argue we label it as a sale. Could be used to track registration for events that do not have a cost.

I know this. As it stands the methods are just stubs that don't fail completely when called. We need to decide how sale/payment is determined, but it is not a part of the specification yet.

edit: the only reason they exist was to make it clear what a payment is and what a sale is without going in and looking at it.

**Comment by fishbacon** [comment]
The primary concern is if we can agree on the design so work can start on templates and logic.

**Comment by fishbacon** [comment]
Why is isort failing on travis? It Works on My Machine™.

**Comment by HenrikOssipoff** [comment]
It shouldn't run on your computer;

> from fembers.models import Member
> from catalog.models import Product

These two in `finance.models` are clearly not in alphabetic order.

**Comment by fishbacon** [comment]
Your face, etc.

**Comment by fishbacon** [comment]
See I did not realise that we were using all sorts of fancy smancy arguments on isort.

**Comment by HenrikOssipoff** [comment]
Okay, then I guess I should just learn to do my thing. Damn you, @BoAnd!

@fishbacon as we discussed Friday, I have some concerns regarding this design.

My main concern remains to be why there is s separation of a Listing and a Product. As I see it, this allows to;
- Have one product having multiple numbers to buy from (why would you ever want that?)
- Allows us to override the name of a product on a listing (I could see why we could _potentially_ want this)
- It would allow for the same product to be priced at two different prices, with different numbers and names

It might be because I'm biased from working 3 years in e-commerce, and it might simply be terminology.

You want to be able to have a product, "Julefrokost" but sell two different variants, correct? One could be "Julefrokost incl. 1 bottle of snaps" and one could be "Julefrokost". Am I correct thus far?

Depending on the answer, I will provide further feedback :) If you could possibly supply some different use cases for this product/listing setup, that would be great!

**Comment by fishbacon** [comment]
I actually found my original reasoning when looking at my notes for unrelated reasons:

Having a `Product` which covers the generic beers (Carlsberg, Tuborg, Carlsberg 47, etc.) but multiple `Listing`s would make it possible for us to list a Carlsberg 47 as what it was originally intended to be, purchase code `47` but still have the `Product` just be generic beer. 

This approach of course makes keeping track of sales of individual types of beers a little harder (but we are basically already doing this by unifying them under `14`). 

I also feel like it would make some of the TREO stuff less burdensome but as it stands I have no idea what our plans are with that stuff.

**Comment by HenrikOssipoff** [comment]
But what you are describing there is also possible with the `Tag` model, right? It would just be a tag "Beer" with no numeric value.

As for the numbers, there could simply be an auto incrementing ID, and an actual number that the person decide themself, when creating the product (e.g. 47 for Carlsberg 47). Plus some applied logic when creating, such that the product won't actually end up without a number.

**Comment by mchro** [comment]
IIRC there was some talk that this would be used for a barcode scanner. The product could then have a "keyboard number" and a "barcode number".

**Comment by fishbacon** [comment]
@HenrikOssipoff really we are arguing very small details now. Feel free to change it to match your idea then I will attempt to make up use cases where it falls short.

@mchro I think bar codes should be a separate app introduced later, it really does not need to know about most of the `Product` stuff.

**Pull request merged**
